export const default_unit = {
  id: 1276,
  photos: [
    {
      id: 3496,
      photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/79d0ce4b-f53.jpg',
      thumb: null,
      created_at: '2024-05-10T17:57:42.562184+01:00',
    },
    {
      id: 3497,
      photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/205e4b47-082.jpg',
      thumb: null,
      created_at: '2024-05-10T17:57:42.991776+01:00',
    },
  ],
  invested_users: [],
  project: {
    id: 853,
    amenities: [
      {
        icon: {
          src: '/_next/static/media/stable-power.d9f94d83.png',
          width: 24,
          height: 24,
          blurWidth: 8,
          blurHeight: 8,
          blurDataURL:
            'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAMAAADz0U65AAAAKlBMVEVMaXE9PT08PDw8PDw7Ozs8PDw+Pj48PDw8PDw7Ozs+Pj48PDw9PT0/Pz8qKTsIAAAADXRSTlMAqTeeK4FSCmi53yHABNbKBAAAAAlwSFlzAAALEwAACxMBAJqcGAAAADhJREFUeJwVykkSgDAMBLEe73Hg/9+l0FlgkmSBnYDwxY2pfhZhKm4jagIaD648/c+d6QuW9Q7nAyCtAQknyIaqAAAAAElFTkSuQmCC',
        },
        name: '24 hours Light',
      },
      {
        icon: {
          src: '/_next/static/media/healthicons_security_worker_outline.1cb99168.svg',
          width: 24,
          height: 24,
        },
        name: 'Security',
      },
      {
        icon: {
          src: '/_next/static/media/lounge.129df462.svg',
          width: 24,
          height: 20,
        },
        name: 'Lounge',
      },
    ],
    land_title: 'Governor’s Consent',
    address: 'Km 42, Lekki-Epe Express Way, Oko-Ado, Sangotedo, Ajah, Lagos',
    latitude: 6.436768340079665,
    longitude: 3.5922785904099923,
    description:
      'You get to live in Lagos and yet away from it. The Urban Prime 3 is a tranquil environment that is close to nature yet accessible from Lekki Epe Expressway',
    name: 'Urban Prime Three',
    profile: null,
    building_type: 'Parcel of Land',
    photo_urls: [
      'https://d1tfxqgzlmg1r3.cloudfront.net/LwDwiFn5kL.jpeg',
      'https://d1tfxqgzlmg1r3.cloudfront.net/QV4beLcoqT.jpeg',
    ],
    contact_persons: [
      {
        id: 370,
        img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
        last_activity: '2024-10-01T22:14:09.048402Z',
        phone_number: '+2348132470992',
        name: 'Joseph Oladokun',
        email: 'johemas161@deligy.com',
        role: 'Admin',
        status: 'accepted',
        invited_on: '2024-05-02T18:13:48.989261+01:00',
        contact_for: 1330,
        business: null,
      },
    ],
    fraction_is_available: false,
  },
  has_allocations: false,
  property_document: [
    {
      id: 2372,
      document_file:
        'https://matador-bucket.s3.amazonaws.com/media/projects/documents/e156c785-178.pdf',
      document_url: null,
      purpose: 'outright',
      created_at: '2024-05-10T17:59:19.748115+01:00',
      project: null,
      plan: null,
      unit: 1276,
    },
  ],
  fees: [],
  total_purchased_fractional_units: 0,
  unit_packet: [],
  unique_ref: null,
  unit_size: '300',
  deed_title: null,
  unit_description:
    'The Urban Prime 3 is a tranquil environment that is close to nature yet accessible from Lekki Epe Expressway',
  deed_file: null,
  price: '50000000.00',
  price_per_fraction: '0.00',
  cash_on_cash_yield: null,
  rental_yield: null,
  status: true,
  display_price: true,
  purchased: false,
  on_sale_as_fractions: false,
  priority_level: null,
  total_fractions: 0,
  total_investors: 0,
  total_purchased_units: 0,
  total_purchased_fractions: 0,
  total_archive: 0,
  total_fractionalized_units: 0,
  note: null,
  unit_type: '',
  no_of_bedrooms: 2,
  is_fraction_sale_available: false,
  dividend_payout_type: null,
  holding_period_in_months: null,
  next_settlement_date: null,
  is_qualified_for_mortgage: false,
  unit_title: '300SQM',
  created_at: '2024-05-02T19:19:30.219871+01:00',
  quantity: 5,
  total_quantity: 5,
  open_house_date: null,
  is_archive: false,
  is_private: false,
  strategy: 'buy_for_hold',
  holding_period: '',
  allow_insurance: false,
  allocation_type: 'manual',
  allocation_milestone: '30.00',
  youtube_url: null,
};

export const default_listing = {
  id: 853,
  photos: [
    {
      photo: 'https://d1tfxqgzlmg1r3.cloudfront.net/LwDwiFn5kL.jpeg',
    },
    {
      photo: 'https://d1tfxqgzlmg1r3.cloudfront.net/QV4beLcoqT.jpeg',
    },
  ],
  created_by: {
    id: 1330,
    first_name: 'Joseph',
    last_name: 'Oladokun',
    email: 'johemas161@deligy.com',
  },
  last_updated_by: {
    id: 1330,
    first_name: 'Joseph',
    last_name: 'Oladokun',
    email: 'johemas161@deligy.com',
  },
  total_units: 5,
  rejected_by: null,
  units_available: 5,
  units_sold: 0,
  is_sold_out: false,
  unit_id: null,
  contact_persons: [
    {
      id: 370,
      img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
      last_activity: '2024-10-01T22:14:09.048402Z',
      phone_number: '+2348132470992',
      name: 'Joseph Oladokun',
      email: 'johemas161@deligy.com',
      role: 'Admin',
      status: 'accepted',
      invited_on: '2024-05-02T18:13:48.989261+01:00',
      contact_for: 1330,
      business: null,
    },
  ],
  display_price: true,
  starting_from: 50000000,
  is_watchlist: false,
  amenities: [
    {
      icon: {
        src: '/_next/static/media/stable-power.d9f94d83.png',
        width: 24,
        height: 24,
        blurWidth: 8,
        blurHeight: 8,
        blurDataURL:
          'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAMAAADz0U65AAAAKlBMVEVMaXE9PT08PDw8PDw7Ozs8PDw+Pj48PDw8PDw7Ozs+Pj48PDw9PT0/Pz8qKTsIAAAADXRSTlMAqTeeK4FSCmi53yHABNbKBAAAAAlwSFlzAAALEwAACxMBAJqcGAAAADhJREFUeJwVykkSgDAMBLEe73Hg/9+l0FlgkmSBnYDwxY2pfhZhKm4jagIaD648/c+d6QuW9Q7nAyCtAQknyIaqAAAAAElFTkSuQmCC',
      },
      name: '24 hours Light',
    },
    {
      icon: {
        src: '/_next/static/media/healthicons_security_worker_outline.1cb99168.svg',
        width: 24,
        height: 24,
      },
      name: 'Security',
    },
    {
      icon: {
        src: '/_next/static/media/lounge.129df462.svg',
        width: 24,
        height: 20,
      },
      name: 'Lounge',
    },
  ],
  is_fractionalized: false,
  project_display_price: true,
  country: {
    id: 1,
    image: 'https://matador-bucket.s3.amazonaws.com/media/country/32ddb759-877.png',
    name: 'Nigeria',
    description: null,
    code: '+234',
    created_at: '2021-11-19T15:59:34.621000+01:00',
    updated_at: '2022-03-14T10:32:12.639000+01:00',
    status: 'active',
  },
  property_document: [
    {
      id: 2372,
      document_file:
        'https://matador-bucket.s3.amazonaws.com/media/projects/documents/e156c785-178.pdf',
      document_url: null,
      purpose: 'outright',
      created_at: '2024-05-10T17:59:19.748115+01:00',
      project: null,
      plan: null,
      unit: 1276,
    },
    {
      id: 2318,
      document_file:
        'https://matador-bucket.s3.amazonaws.com/media/projects/documents/a8c8426b-fc9.pdf',
      document_url: 'https://d1tfxqgzlmg1r3.cloudfront.net/ShCOyN4n47.pdf',
      purpose: 'brochure',
      created_at: '2024-05-02T19:19:30.886068+01:00',
      project: 853,
      plan: null,
      unit: 1276,
    },
    {
      id: 2317,
      document_file: null,
      document_url: 'https://d1tfxqgzlmg1r3.cloudfront.net/GOebKbENFH.pdf',
      purpose: 'brochure',
      created_at: '2024-05-02T19:14:50.861947+01:00',
      project: 853,
      plan: null,
      unit: null,
    },
  ],
  payment_plan_is_available: false,
  pinned: false,
  project_packet: [],
  name: 'Urban Prime Three',
  land_size: '1000',
  is_unit: false,
  property_class: null,
  project_start_date: null,
  completed_timestamp: null,
  fractions_progress_bar: true,
  maps_view: true,
  constructed_by: 'Landwey',
  land_title: 'Governor’s Consent',
  description:
    'You get to live in Lagos and yet away from it. The Urban Prime 3 is a tranquil environment that is close to nature yet accessible from Lekki Epe Expressway',
  address: 'Km 42, Lekki-Epe Express Way, Oko-Ado, Sangotedo, Ajah, Lagos',
  profile: null,
  landmark: 'Ajah, Lagos',
  building_type: 'Parcel of Land',
  inspection_enabled: true,
  income_start_timestamp: null,
  status: 'In Construction',
  year_built: null,
  start_period: 'May',
  start_year: '2023',
  end_period: 'Q1',
  end_year: '2025',
  youtube_url: '',
  location_description: null,
  longitude: 3.5922785904099923,
  latitude: 6.436768340079665,
  created_at: '2024-05-02T19:14:50.828653+01:00',
  updated_at: '2024-05-10T17:56:43.736122+01:00',
  publish: false,
  rejected: false,
  request_for_publish: true,
  publish_to_store: true,
  rejection_reason: null,
  photo_urls: [
    'https://d1tfxqgzlmg1r3.cloudfront.net/LwDwiFn5kL.jpeg',
    'https://d1tfxqgzlmg1r3.cloudfront.net/QV4beLcoqT.jpeg',
  ],
  open_to_subscription: false,
  star_rating: 0,
  fraction_is_available: false,
  open_house_date: null,
  is_private: false,
  project_archived: false,
  total_archive: null,
  internal_commission_rate: '5.00',
  external_commission_rate: '7.00',
  current_fraction_price: '0.00',
  business: 213,
  reels: [],
};

export const default_portfolio = [
  {
    id: 4192,
    unit: {
      id: 1305,
      photos: [
        {
          id: 3506,
          photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/371d320a-8f6.jpg',
          thumb: null,
          created_at: '2024-05-13T12:01:08.689715+01:00',
        },
      ],
      invested_users: [],
      project: {
        id: 876,
        amenities: [],
        land_title: "Governor's Consent",
        address: 'Lekki-Epe, Lagos',
        latitude: 6.43051,
        longitude: 3.46088,
        description:
          'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
        name: 'Lakowe country reserve',
        profile: null,
        building_type: 'Estate',
        photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
        contact_persons: [
          {
            id: 370,
            img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
            last_activity: '2024-10-01T22:14:09.048402Z',
            phone_number: '+2348132470992',
            name: 'Joseph Oladokun',
            email: 'johemas161@deligy.com',
            role: 'Admin',
            status: 'accepted',
            invited_on: '2024-05-02T18:13:48.989261+01:00',
            contact_for: 1330,
            business: null,
          },
        ],
        fraction_is_available: false,
      },
      has_allocations: false,
      property_document: [
        {
          id: 2391,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T12:01:08.945411+01:00',
          project: 876,
          plan: null,
          unit: 1305,
        },
      ],
      fees: [],
      total_purchased_fractional_units: 0,
      unit_packet: [],
      unique_ref: null,
      unit_size: '300',
      deed_title: null,
      unit_description:
        'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
      deed_file: null,
      price: '40000000.00',
      price_per_fraction: '0.00',
      cash_on_cash_yield: null,
      rental_yield: null,
      status: true,
      display_price: true,
      purchased: false,
      on_sale_as_fractions: false,
      priority_level: null,
      total_fractions: 0,
      total_investors: 0,
      total_purchased_units: 6,
      total_purchased_fractions: 0,
      total_archive: 0,
      total_fractionalized_units: 0,
      note: null,
      unit_type: '',
      no_of_bedrooms: 0,
      is_fraction_sale_available: false,
      dividend_payout_type: null,
      holding_period_in_months: null,
      next_settlement_date: null,
      is_qualified_for_mortgage: false,
      unit_title: '300SQM',
      created_at: '2024-05-13T12:01:08.458479+01:00',
      quantity: 4,
      total_quantity: 10,
      open_house_date: null,
      is_archive: false,
      is_private: false,
      strategy: 'buy_for_hold',
      holding_period: '',
      allow_insurance: false,
      allocation_type: 'manual',
      allocation_milestone: '30.00',
      youtube_url: null,
    },
    payment_plan: {
      id: 1427,
      bundle: {
        id: 1305,
        photos: [
          {
            id: 3506,
            photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/371d320a-8f6.jpg',
            thumb: null,
            created_at: '2024-05-13T12:01:08.689715+01:00',
          },
        ],
        invested_users: [],
        project: {
          id: 876,
          amenities: [],
          land_title: "Governor's Consent",
          address: 'Lekki-Epe, Lagos',
          latitude: 6.43051,
          longitude: 3.46088,
          description:
            'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
          name: 'Lakowe country reserve',
          profile: null,
          building_type: 'Estate',
          photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
          contact_persons: [
            {
              id: 370,
              img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
              last_activity: '2024-10-01T22:14:09.048402Z',
              phone_number: '+2348132470992',
              name: 'Joseph Oladokun',
              email: 'johemas161@deligy.com',
              role: 'Admin',
              status: 'accepted',
              invited_on: '2024-05-02T18:13:48.989261+01:00',
              contact_for: 1330,
              business: null,
            },
          ],
          fraction_is_available: false,
        },
        has_allocations: false,
        property_document: [
          {
            id: 2391,
            document_file:
              'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
            document_url: null,
            purpose: 'outright',
            created_at: '2024-05-13T12:01:08.945411+01:00',
            project: 876,
            plan: null,
            unit: 1305,
          },
        ],
        fees: [],
        total_purchased_fractional_units: 0,
        unit_packet: [],
        unique_ref: null,
        unit_size: '300',
        deed_title: null,
        unit_description:
          'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
        deed_file: null,
        price: '40000000.00',
        price_per_fraction: '0.00',
        cash_on_cash_yield: null,
        rental_yield: null,
        status: true,
        display_price: true,
        purchased: false,
        on_sale_as_fractions: false,
        priority_level: null,
        total_fractions: 0,
        total_investors: 0,
        total_purchased_units: 6,
        total_purchased_fractions: 0,
        total_archive: 0,
        total_fractionalized_units: 0,
        note: null,
        unit_type: '',
        no_of_bedrooms: 0,
        is_fraction_sale_available: false,
        dividend_payout_type: null,
        holding_period_in_months: null,
        next_settlement_date: null,
        is_qualified_for_mortgage: false,
        unit_title: '300SQM',
        created_at: '2024-05-13T12:01:08.458479+01:00',
        quantity: 4,
        total_quantity: 10,
        open_house_date: null,
        is_archive: false,
        is_private: false,
        strategy: 'buy_for_hold',
        holding_period: '',
        allow_insurance: false,
        allocation_type: 'manual',
        allocation_milestone: '30.00',
        youtube_url: null,
      },
      contract: [
        'https://matador-bucket.s3.amazonaws.com/media/projects/documents/999099d2-2f0.pdf',
      ],
      purchase_price: '1000.00',
      interest_rate: '0.00000000',
      max_duration_in_months: 3,
      grace_period_in_months: 3,
      payment_period_in_months: 9,
      due_period_in_months: 3,
      initial_deposit_in_percentage: 0,
      initial_deposit_in_value: '100.00',
      payment_frequency: 'monthly',
      plan_type: 'manual',
      periodic_payment: '100.00',
      cost_of_funds: '0.00',
      unprocessed_paymentplan: false,
      is_private: true,
    },
    project: {
      id: 876,
      photos: [
        {
          photo: 'https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg',
        },
      ],
      created_by: {
        id: 1330,
        first_name: 'Joseph',
        last_name: 'Oladokun',
        email: 'johemas161@deligy.com',
      },
      last_updated_by: {
        id: 1330,
        first_name: 'Joseph',
        last_name: 'Oladokun',
        email: 'johemas161@deligy.com',
      },
      rejected_by: null,
      is_sold_out: false,
      unit_id: null,
      contact_persons: [
        {
          id: 370,
          img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
          last_activity: '2024-10-01T22:14:09.048402Z',
          phone_number: '+2348132470992',
          name: 'Joseph Oladokun',
          email: 'johemas161@deligy.com',
          role: 'Admin',
          status: 'accepted',
          invited_on: '2024-05-02T18:13:48.989261+01:00',
          contact_for: 1330,
          business: null,
        },
      ],
      display_price: true,
      starting_from: 40000000,
      is_watchlist: false,
      amenities: [],
      is_fractionalized: true,
      project_display_price: true,
      country: {
        id: 1,
        image: 'https://matador-bucket.s3.amazonaws.com/media/country/32ddb759-877.png',
        name: 'Nigeria',
        description: null,
        code: '+234',
        created_at: '2021-11-19T15:59:34.621000+01:00',
        updated_at: '2022-03-14T10:32:12.639000+01:00',
        status: 'active',
      },
      property_document: [
        {
          id: 2401,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/34059124-0a5.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T13:02:37.051015+01:00',
          project: 876,
          plan: null,
          unit: 1307,
        },
        {
          id: 2391,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T12:01:08.945411+01:00',
          project: 876,
          plan: null,
          unit: 1305,
        },
        {
          id: 2390,
          document_file: null,
          document_url: 'https://d1tfxqgzlmg1r3.cloudfront.net/km8Nr1xNrp.pdf',
          purpose: 'brochure',
          created_at: '2024-05-13T11:59:19.099872+01:00',
          project: 876,
          plan: null,
          unit: null,
        },
      ],
      payment_plan_is_available: true,
      pinned: false,
      project_packet: [],
      name: 'Lakowe country reserve',
      land_size: '3080000',
      is_unit: false,
      property_class: null,
      project_start_date: null,
      completed_timestamp: null,
      fractions_progress_bar: true,
      maps_view: true,
      constructed_by: 'Landwey',
      land_title: "Governor's Consent",
      description:
        'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
      address: 'Lekki-Epe, Lagos',
      profile: null,
      landmark: 'Lekki-Epe, Lagos',
      building_type: 'Estate',
      inspection_enabled: true,
      income_start_timestamp: null,
      status: 'Pre Construction',
      year_built: null,
      start_period: 'Q4',
      start_year: '2024',
      end_period: 'Q4',
      end_year: '2030',
      youtube_url: '',
      location_description: null,
      longitude: 3.46088,
      latitude: 6.43051,
      created_at: '2024-05-13T11:59:19.045227+01:00',
      updated_at: '2024-05-13T13:11:10.355413+01:00',
      publish: false,
      rejected: false,
      request_for_publish: true,
      publish_to_store: true,
      rejection_reason: null,
      photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
      open_to_subscription: false,
      star_rating: 0,
      fraction_is_available: false,
      open_house_date: null,
      is_private: false,
      project_archived: false,
      total_archive: null,
      internal_commission_rate: '2.00',
      external_commission_rate: '3.00',
      current_fraction_price: '0.00',
      business: 213,
      reels: [],
    },
    allocation: null,
    co_owners: [],
    fractional_equity_value: null,
    amount_of_fractions: null,
    fractions_amount_paid: null,
    owner: {
      customer_info: null,
      id: 1258,
      bvn: null,
      agent_id: null,
      username: null,
      approved_at: null,
      date_of_birth: '2006-04-07',
      first_name: 'Joseph',
      last_name: 'Oladokun',
      middle_name: 'Abidemi',
      user_status: 'Active',
      phone: '+23408132470992',
      is_mfa: false,
      avatar: 'https://matador-bucket.s3.amazonaws.com/media/4bd539d8-0b5.png',
      monthly_income: null,
      email: 'mistyladee00@gmail.com',
      address: null,
      gender: 'Male',
      occupation: null,
      marital_status: null,
      company_name: null,
      yearly_income: null,
      highest_education: null,
      employment_status: null,
      sign_up_time: '2024-04-02T15:15:49.231657+01:00',
      company_address: null,
    },
    payment_status: 'defaulting',
    can_allocate: false,
    extra_coownership_data: null,
    equity_fees: [],
    customer: {
      id: 886,
      avatar: 'https://matador-bucket.s3.amazonaws.com/media/customer_avatar/8b89848f-72d.png',
      active: false,
      customer_ref: null,
      blacklisted: false,
      refunded_balance: '0.00',
      utility_bill: 'https://matador-bucket.s3.amazonaws.com/media/Raw%20content',
      utility_bill_updated_at: null,
      is_tier3: false,
      gender: 'Male',
      referred_at: '2024-06-22T16:27:29.744309+01:00',
      created_at: '2024-06-22T16:27:29.744330+01:00',
      password:
        'pbkdf2_sha256$260000$CSoU8F98YdMjdqqB1uHK1z$HxaBe9hxxHYhvRA1lgITcqQAFlDDI0XJlHE0CE+4aM4=',
      highest_education: null,
      address: null,
      employment_status: null,
      monthly_income: null,
      yearly_income: null,
      occupation: null,
      marital_status: null,
      company_name: null,
      company_address: null,
      email: 'mistyladee00@gmail.com',
      first_name: 'Joseph ',
      last_name: 'Oladokun ',
      middle_name: 'Abidemi ',
      phone: '8132470992',
      year_of_birth: null,
      bvn: null,
      email_verified: false,
      date_of_birth: null,
      outreach: null,
      username: null,
      extended_user: true,
      biometric_authentication: false,
      is_blocked: false,
      status: false,
      push_notification_allowed: false,
      user: 1258,
      developer: 1330,
      business: 213,
      referred_by: null,
      country: 1,
      created_by: null,
    },
    customer_co_owners: [],
    validation_requests: [],
    approved_agent: null,
    purchase_date: null,
    offer_by: null,
    total_due_balance: 99.22,
    offer_price: 1000,
    transaction_fee: '0.00',
    is_disputed: false,
    fractions_distributed: 0,
    fractions_left: 0,
    total_unit_price: '1000.00',
    auto_debit: false,
    auto_pay: false,
    next_due_balance: '99.22',
    next_due_date: '2024-07-23T18:53:58.240062+01:00',
    payment_complete: false,
    amount_paid: '100.78',
    created_at: '2024-06-24T18:51:02.179619+01:00',
    current_outstanding_balance: '899.22',
    status: 'PAID',
    type: 'WHOLE',
    auto_debit_frequency: 'DAILY',
    auto_debit_source: 'card',
    deed_requested: false,
    deed_title: null,
    deed_file: null,
    auto_debit_amount: '0.00',
    deed_granted: false,
    start_date: null,
    final_due_date: '2025-03-21T18:51:02.176854+01:00',
    purchased_from_matador: false,
    equity_value: 100,
    equity_value_invitable: 100,
    requested_at: null,
    uploaded_at: null,
    offer_expires: '2024-06-25T18:51:02.178988+01:00',
    offer_started: true,
    all_invitees_accepted: false,
    matador_junior: false,
    has_generated_upcoming: true,
    is_offer: false,
    deduct_from: 'available',
    card: null,
    uploaded_by: null,
    initiator: null,
    co_parent: [],
    account_numbers: [],
  },
  {
    id: 4191,
    unit: {
      id: 1305,
      photos: [
        {
          id: 3506,
          photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/371d320a-8f6.jpg',
          thumb: null,
          created_at: '2024-05-13T12:01:08.689715+01:00',
        },
      ],
      invested_users: [],
      project: {
        id: 876,
        amenities: [],
        land_title: "Governor's Consent",
        address: 'Lekki-Epe, Lagos',
        latitude: 6.43051,
        longitude: 3.46088,
        description:
          'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
        name: 'Lakowe country reserve',
        profile: null,
        building_type: 'Estate',
        photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
        contact_persons: [
          {
            id: 370,
            img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
            last_activity: '2024-10-01T22:14:09.048402Z',
            phone_number: '+2348132470992',
            name: 'Joseph Oladokun',
            email: 'johemas161@deligy.com',
            role: 'Admin',
            status: 'accepted',
            invited_on: '2024-05-02T18:13:48.989261+01:00',
            contact_for: 1330,
            business: null,
          },
        ],
        fraction_is_available: false,
      },
      has_allocations: false,
      property_document: [
        {
          id: 2391,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T12:01:08.945411+01:00',
          project: 876,
          plan: null,
          unit: 1305,
        },
      ],
      fees: [],
      total_purchased_fractional_units: 0,
      unit_packet: [],
      unique_ref: null,
      unit_size: '300',
      deed_title: null,
      unit_description:
        'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
      deed_file: null,
      price: '40000000.00',
      price_per_fraction: '0.00',
      cash_on_cash_yield: null,
      rental_yield: null,
      status: true,
      display_price: true,
      purchased: false,
      on_sale_as_fractions: false,
      priority_level: null,
      total_fractions: 0,
      total_investors: 0,
      total_purchased_units: 6,
      total_purchased_fractions: 0,
      total_archive: 0,
      total_fractionalized_units: 0,
      note: null,
      unit_type: '',
      no_of_bedrooms: 0,
      is_fraction_sale_available: false,
      dividend_payout_type: null,
      holding_period_in_months: null,
      next_settlement_date: null,
      is_qualified_for_mortgage: false,
      unit_title: '300SQM',
      created_at: '2024-05-13T12:01:08.458479+01:00',
      quantity: 4,
      total_quantity: 10,
      open_house_date: null,
      is_archive: false,
      is_private: false,
      strategy: 'buy_for_hold',
      holding_period: '',
      allow_insurance: false,
      allocation_type: 'manual',
      allocation_milestone: '30.00',
      youtube_url: null,
    },
    payment_plan: {
      id: 1425,
      bundle: {
        id: 1305,
        photos: [
          {
            id: 3506,
            photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/371d320a-8f6.jpg',
            thumb: null,
            created_at: '2024-05-13T12:01:08.689715+01:00',
          },
        ],
        invested_users: [],
        project: {
          id: 876,
          amenities: [],
          land_title: "Governor's Consent",
          address: 'Lekki-Epe, Lagos',
          latitude: 6.43051,
          longitude: 3.46088,
          description:
            'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
          name: 'Lakowe country reserve',
          profile: null,
          building_type: 'Estate',
          photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
          contact_persons: [
            {
              id: 370,
              img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
              last_activity: '2024-10-01T22:14:09.048402Z',
              phone_number: '+2348132470992',
              name: 'Joseph Oladokun',
              email: 'johemas161@deligy.com',
              role: 'Admin',
              status: 'accepted',
              invited_on: '2024-05-02T18:13:48.989261+01:00',
              contact_for: 1330,
              business: null,
            },
          ],
          fraction_is_available: false,
        },
        has_allocations: false,
        property_document: [
          {
            id: 2391,
            document_file:
              'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
            document_url: null,
            purpose: 'outright',
            created_at: '2024-05-13T12:01:08.945411+01:00',
            project: 876,
            plan: null,
            unit: 1305,
          },
        ],
        fees: [],
        total_purchased_fractional_units: 0,
        unit_packet: [],
        unique_ref: null,
        unit_size: '300',
        deed_title: null,
        unit_description:
          'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
        deed_file: null,
        price: '40000000.00',
        price_per_fraction: '0.00',
        cash_on_cash_yield: null,
        rental_yield: null,
        status: true,
        display_price: true,
        purchased: false,
        on_sale_as_fractions: false,
        priority_level: null,
        total_fractions: 0,
        total_investors: 0,
        total_purchased_units: 6,
        total_purchased_fractions: 0,
        total_archive: 0,
        total_fractionalized_units: 0,
        note: null,
        unit_type: '',
        no_of_bedrooms: 0,
        is_fraction_sale_available: false,
        dividend_payout_type: null,
        holding_period_in_months: null,
        next_settlement_date: null,
        is_qualified_for_mortgage: false,
        unit_title: '300SQM',
        created_at: '2024-05-13T12:01:08.458479+01:00',
        quantity: 4,
        total_quantity: 10,
        open_house_date: null,
        is_archive: false,
        is_private: false,
        strategy: 'buy_for_hold',
        holding_period: '',
        allow_insurance: false,
        allocation_type: 'manual',
        allocation_milestone: '30.00',
        youtube_url: null,
      },
      contract: [
        'https://matador-bucket.s3.amazonaws.com/media/projects/documents/dc91c45e-c06.pdf',
      ],
      purchase_price: '400.00',
      interest_rate: '0.00000000',
      max_duration_in_months: 3,
      grace_period_in_months: 3,
      payment_period_in_months: 3,
      due_period_in_months: 3,
      initial_deposit_in_percentage: 0,
      initial_deposit_in_value: '100.00',
      payment_frequency: 'monthly',
      plan_type: 'manual',
      periodic_payment: '100.00',
      cost_of_funds: '0.00',
      unprocessed_paymentplan: false,
      is_private: false,
    },
    project: {
      id: 876,
      photos: [
        {
          photo: 'https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg',
        },
      ],
      created_by: {
        id: 1330,
        first_name: 'Joseph',
        last_name: 'Oladokun',
        email: 'johemas161@deligy.com',
      },
      last_updated_by: {
        id: 1330,
        first_name: 'Joseph',
        last_name: 'Oladokun',
        email: 'johemas161@deligy.com',
      },
      rejected_by: null,
      is_sold_out: false,
      unit_id: null,
      contact_persons: [
        {
          id: 370,
          img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
          last_activity: '2024-10-01T22:14:09.048402Z',
          phone_number: '+2348132470992',
          name: 'Joseph Oladokun',
          email: 'johemas161@deligy.com',
          role: 'Admin',
          status: 'accepted',
          invited_on: '2024-05-02T18:13:48.989261+01:00',
          contact_for: 1330,
          business: null,
        },
      ],
      display_price: true,
      starting_from: 40000000,
      is_watchlist: false,
      amenities: [],
      is_fractionalized: true,
      project_display_price: true,
      country: {
        id: 1,
        image: 'https://matador-bucket.s3.amazonaws.com/media/country/32ddb759-877.png',
        name: 'Nigeria',
        description: null,
        code: '+234',
        created_at: '2021-11-19T15:59:34.621000+01:00',
        updated_at: '2022-03-14T10:32:12.639000+01:00',
        status: 'active',
      },
      property_document: [
        {
          id: 2401,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/34059124-0a5.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T13:02:37.051015+01:00',
          project: 876,
          plan: null,
          unit: 1307,
        },
        {
          id: 2391,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T12:01:08.945411+01:00',
          project: 876,
          plan: null,
          unit: 1305,
        },
        {
          id: 2390,
          document_file: null,
          document_url: 'https://d1tfxqgzlmg1r3.cloudfront.net/km8Nr1xNrp.pdf',
          purpose: 'brochure',
          created_at: '2024-05-13T11:59:19.099872+01:00',
          project: 876,
          plan: null,
          unit: null,
        },
      ],
      payment_plan_is_available: true,
      pinned: false,
      project_packet: [],
      name: 'Lakowe country reserve',
      land_size: '3080000',
      is_unit: false,
      property_class: null,
      project_start_date: null,
      completed_timestamp: null,
      fractions_progress_bar: true,
      maps_view: true,
      constructed_by: 'Landwey',
      land_title: "Governor's Consent",
      description:
        'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
      address: 'Lekki-Epe, Lagos',
      profile: null,
      landmark: 'Lekki-Epe, Lagos',
      building_type: 'Estate',
      inspection_enabled: true,
      income_start_timestamp: null,
      status: 'Pre Construction',
      year_built: null,
      start_period: 'Q4',
      start_year: '2024',
      end_period: 'Q4',
      end_year: '2030',
      youtube_url: '',
      location_description: null,
      longitude: 3.46088,
      latitude: 6.43051,
      created_at: '2024-05-13T11:59:19.045227+01:00',
      updated_at: '2024-05-13T13:11:10.355413+01:00',
      publish: false,
      rejected: false,
      request_for_publish: true,
      publish_to_store: true,
      rejection_reason: null,
      photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
      open_to_subscription: false,
      star_rating: 0,
      fraction_is_available: false,
      open_house_date: null,
      is_private: false,
      project_archived: false,
      total_archive: null,
      internal_commission_rate: '2.00',
      external_commission_rate: '3.00',
      current_fraction_price: '0.00',
      business: 213,
      reels: [],
    },
    allocation: null,
    co_owners: [],
    fractional_equity_value: null,
    amount_of_fractions: null,
    fractions_amount_paid: null,
    owner: {
      customer_info: null,
      id: 1258,
      bvn: null,
      agent_id: null,
      username: null,
      approved_at: null,
      date_of_birth: '2006-04-07',
      first_name: 'Joseph',
      last_name: 'Oladokun',
      middle_name: 'Abidemi',
      user_status: 'Active',
      phone: '+23408132470992',
      is_mfa: false,
      avatar: 'https://matador-bucket.s3.amazonaws.com/media/4bd539d8-0b5.png',
      monthly_income: null,
      email: 'mistyladee00@gmail.com',
      address: null,
      gender: 'Male',
      occupation: null,
      marital_status: null,
      company_name: null,
      yearly_income: null,
      highest_education: null,
      employment_status: null,
      sign_up_time: '2024-04-02T15:15:49.231657+01:00',
      company_address: null,
    },
    payment_status: 'defaulting',
    can_allocate: false,
    extra_coownership_data: null,
    equity_fees: [],
    customer: {
      id: 886,
      avatar: 'https://matador-bucket.s3.amazonaws.com/media/customer_avatar/8b89848f-72d.png',
      active: false,
      customer_ref: null,
      blacklisted: false,
      refunded_balance: '0.00',
      utility_bill: 'https://matador-bucket.s3.amazonaws.com/media/Raw%20content',
      utility_bill_updated_at: null,
      is_tier3: false,
      gender: 'Male',
      referred_at: '2024-06-22T16:27:29.744309+01:00',
      created_at: '2024-06-22T16:27:29.744330+01:00',
      password:
        'pbkdf2_sha256$260000$CSoU8F98YdMjdqqB1uHK1z$HxaBe9hxxHYhvRA1lgITcqQAFlDDI0XJlHE0CE+4aM4=',
      highest_education: null,
      address: null,
      employment_status: null,
      monthly_income: null,
      yearly_income: null,
      occupation: null,
      marital_status: null,
      company_name: null,
      company_address: null,
      email: 'mistyladee00@gmail.com',
      first_name: 'Joseph ',
      last_name: 'Oladokun ',
      middle_name: 'Abidemi ',
      phone: '8132470992',
      year_of_birth: null,
      bvn: null,
      email_verified: false,
      date_of_birth: null,
      outreach: null,
      username: null,
      extended_user: true,
      biometric_authentication: false,
      is_blocked: false,
      status: false,
      push_notification_allowed: false,
      user: 1258,
      developer: 1330,
      business: 213,
      referred_by: null,
      country: 1,
      created_by: null,
    },
    customer_co_owners: [],
    validation_requests: [],
    approved_agent: null,
    purchase_date: null,
    offer_by: null,
    total_due_balance: 99.22,
    offer_price: 400,
    transaction_fee: '0.00',
    is_disputed: false,
    fractions_distributed: 0,
    fractions_left: 0,
    total_unit_price: '400.00',
    auto_debit: false,
    auto_pay: false,
    next_due_balance: '99.22',
    next_due_date: '2024-07-23T18:47:02.862957+01:00',
    payment_complete: false,
    amount_paid: '100.78',
    created_at: '2024-06-24T18:43:25.883012+01:00',
    current_outstanding_balance: '299.22',
    status: 'PAID',
    type: 'WHOLE',
    auto_debit_frequency: 'DAILY',
    auto_debit_source: 'card',
    deed_requested: false,
    deed_title: null,
    deed_file: null,
    auto_debit_amount: '0.00',
    deed_granted: false,
    start_date: null,
    final_due_date: '2024-09-22T18:43:25.880147+01:00',
    purchased_from_matador: false,
    equity_value: 100,
    equity_value_invitable: 100,
    requested_at: null,
    uploaded_at: null,
    offer_expires: '2024-06-25T18:43:25.882188+01:00',
    offer_started: true,
    all_invitees_accepted: false,
    matador_junior: false,
    has_generated_upcoming: true,
    is_offer: false,
    deduct_from: 'available',
    card: null,
    uploaded_by: null,
    initiator: null,
    co_parent: [],
    account_numbers: [],
  },
  {
    id: 4179,
    unit: {
      id: 1305,
      photos: [
        {
          id: 3506,
          photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/371d320a-8f6.jpg',
          thumb: null,
          created_at: '2024-05-13T12:01:08.689715+01:00',
        },
      ],
      invested_users: [],
      project: {
        id: 876,
        amenities: [],
        land_title: "Governor's Consent",
        address: 'Lekki-Epe, Lagos',
        latitude: 6.43051,
        longitude: 3.46088,
        description:
          'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
        name: 'Lakowe country reserve',
        profile: null,
        building_type: 'Estate',
        photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
        contact_persons: [
          {
            id: 370,
            img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
            last_activity: '2024-10-01T22:14:09.048402Z',
            phone_number: '+2348132470992',
            name: 'Joseph Oladokun',
            email: 'johemas161@deligy.com',
            role: 'Admin',
            status: 'accepted',
            invited_on: '2024-05-02T18:13:48.989261+01:00',
            contact_for: 1330,
            business: null,
          },
        ],
        fraction_is_available: false,
      },
      has_allocations: false,
      property_document: [
        {
          id: 2391,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T12:01:08.945411+01:00',
          project: 876,
          plan: null,
          unit: 1305,
        },
      ],
      fees: [],
      total_purchased_fractional_units: 0,
      unit_packet: [],
      unique_ref: null,
      unit_size: '300',
      deed_title: null,
      unit_description:
        'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
      deed_file: null,
      price: '40000000.00',
      price_per_fraction: '0.00',
      cash_on_cash_yield: null,
      rental_yield: null,
      status: true,
      display_price: true,
      purchased: false,
      on_sale_as_fractions: false,
      priority_level: null,
      total_fractions: 0,
      total_investors: 0,
      total_purchased_units: 6,
      total_purchased_fractions: 0,
      total_archive: 0,
      total_fractionalized_units: 0,
      note: null,
      unit_type: '',
      no_of_bedrooms: 0,
      is_fraction_sale_available: false,
      dividend_payout_type: null,
      holding_period_in_months: null,
      next_settlement_date: null,
      is_qualified_for_mortgage: false,
      unit_title: '300SQM',
      created_at: '2024-05-13T12:01:08.458479+01:00',
      quantity: 4,
      total_quantity: 10,
      open_house_date: null,
      is_archive: false,
      is_private: false,
      strategy: 'buy_for_hold',
      holding_period: '',
      allow_insurance: false,
      allocation_type: 'manual',
      allocation_milestone: '30.00',
      youtube_url: null,
    },
    payment_plan: {
      id: 1422,
      bundle: {
        id: 1305,
        photos: [
          {
            id: 3506,
            photo: 'https://matador-bucket.s3.amazonaws.com/media/project/photo/371d320a-8f6.jpg',
            thumb: null,
            created_at: '2024-05-13T12:01:08.689715+01:00',
          },
        ],
        invested_users: [],
        project: {
          id: 876,
          amenities: [],
          land_title: "Governor's Consent",
          address: 'Lekki-Epe, Lagos',
          latitude: 6.43051,
          longitude: 3.46088,
          description:
            'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
          name: 'Lakowe country reserve',
          profile: null,
          building_type: 'Estate',
          photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
          contact_persons: [
            {
              id: 370,
              img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
              last_activity: '2024-10-01T22:14:09.048402Z',
              phone_number: '+2348132470992',
              name: 'Joseph Oladokun',
              email: 'johemas161@deligy.com',
              role: 'Admin',
              status: 'accepted',
              invited_on: '2024-05-02T18:13:48.989261+01:00',
              contact_for: 1330,
              business: null,
            },
          ],
          fraction_is_available: false,
        },
        has_allocations: false,
        property_document: [
          {
            id: 2391,
            document_file:
              'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
            document_url: null,
            purpose: 'outright',
            created_at: '2024-05-13T12:01:08.945411+01:00',
            project: 876,
            plan: null,
            unit: 1305,
          },
        ],
        fees: [],
        total_purchased_fractional_units: 0,
        unit_packet: [],
        unique_ref: null,
        unit_size: '300',
        deed_title: null,
        unit_description:
          'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
        deed_file: null,
        price: '40000000.00',
        price_per_fraction: '0.00',
        cash_on_cash_yield: null,
        rental_yield: null,
        status: true,
        display_price: true,
        purchased: false,
        on_sale_as_fractions: false,
        priority_level: null,
        total_fractions: 0,
        total_investors: 0,
        total_purchased_units: 6,
        total_purchased_fractions: 0,
        total_archive: 0,
        total_fractionalized_units: 0,
        note: null,
        unit_type: '',
        no_of_bedrooms: 0,
        is_fraction_sale_available: false,
        dividend_payout_type: null,
        holding_period_in_months: null,
        next_settlement_date: null,
        is_qualified_for_mortgage: false,
        unit_title: '300SQM',
        created_at: '2024-05-13T12:01:08.458479+01:00',
        quantity: 4,
        total_quantity: 10,
        open_house_date: null,
        is_archive: false,
        is_private: false,
        strategy: 'buy_for_hold',
        holding_period: '',
        allow_insurance: false,
        allocation_type: 'manual',
        allocation_milestone: '30.00',
        youtube_url: null,
      },
      contract: [
        'https://matador-bucket.s3.amazonaws.com/media/projects/documents/fa64a328-4aa.pdf',
      ],
      purchase_price: '700.00',
      interest_rate: '0.00000000',
      max_duration_in_months: 3,
      grace_period_in_months: 3,
      payment_period_in_months: 6,
      due_period_in_months: 3,
      initial_deposit_in_percentage: 0,
      initial_deposit_in_value: '100.00',
      payment_frequency: 'monthly',
      plan_type: 'manual',
      periodic_payment: '100.00',
      cost_of_funds: '0.00',
      unprocessed_paymentplan: false,
      is_private: true,
    },
    project: {
      id: 876,
      photos: [
        {
          photo: 'https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg',
        },
      ],
      created_by: {
        id: 1330,
        first_name: 'Joseph',
        last_name: 'Oladokun',
        email: 'johemas161@deligy.com',
      },
      last_updated_by: {
        id: 1330,
        first_name: 'Joseph',
        last_name: 'Oladokun',
        email: 'johemas161@deligy.com',
      },
      rejected_by: null,
      is_sold_out: false,
      unit_id: null,
      contact_persons: [
        {
          id: 370,
          img: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
          last_activity: '2024-10-01T22:14:09.048402Z',
          phone_number: '+2348132470992',
          name: 'Joseph Oladokun',
          email: 'johemas161@deligy.com',
          role: 'Admin',
          status: 'accepted',
          invited_on: '2024-05-02T18:13:48.989261+01:00',
          contact_for: 1330,
          business: null,
        },
      ],
      display_price: true,
      starting_from: 40000000,
      is_watchlist: false,
      amenities: [],
      is_fractionalized: true,
      project_display_price: true,
      country: {
        id: 1,
        image: 'https://matador-bucket.s3.amazonaws.com/media/country/32ddb759-877.png',
        name: 'Nigeria',
        description: null,
        code: '+234',
        created_at: '2021-11-19T15:59:34.621000+01:00',
        updated_at: '2022-03-14T10:32:12.639000+01:00',
        status: 'active',
      },
      property_document: [
        {
          id: 2401,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/34059124-0a5.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T13:02:37.051015+01:00',
          project: 876,
          plan: null,
          unit: 1307,
        },
        {
          id: 2391,
          document_file:
            'https://matador-bucket.s3.amazonaws.com/media/projects/documents/628f15b3-f7e.pdf',
          document_url: null,
          purpose: 'outright',
          created_at: '2024-05-13T12:01:08.945411+01:00',
          project: 876,
          plan: null,
          unit: 1305,
        },
        {
          id: 2390,
          document_file: null,
          document_url: 'https://d1tfxqgzlmg1r3.cloudfront.net/km8Nr1xNrp.pdf',
          purpose: 'brochure',
          created_at: '2024-05-13T11:59:19.099872+01:00',
          project: 876,
          plan: null,
          unit: null,
        },
      ],
      payment_plan_is_available: true,
      pinned: false,
      project_packet: [],
      name: 'Lakowe country reserve',
      land_size: '3080000',
      is_unit: false,
      property_class: null,
      project_start_date: null,
      completed_timestamp: null,
      fractions_progress_bar: true,
      maps_view: true,
      constructed_by: 'Landwey',
      land_title: "Governor's Consent",
      description:
        'Introducing Lakowe Country Reserve, where modern living seamlessly merges with the tranquility of nature. Nestled in the heart of serenity, this exceptional community is designed to elevate your lifestyle, offering a harmonious blend of contemporary comforts and the lush beauty of the surrounding landscape.',
      address: 'Lekki-Epe, Lagos',
      profile: null,
      landmark: 'Lekki-Epe, Lagos',
      building_type: 'Estate',
      inspection_enabled: true,
      income_start_timestamp: null,
      status: 'Pre Construction',
      year_built: null,
      start_period: 'Q4',
      start_year: '2024',
      end_period: 'Q4',
      end_year: '2030',
      youtube_url: '',
      location_description: null,
      longitude: 3.46088,
      latitude: 6.43051,
      created_at: '2024-05-13T11:59:19.045227+01:00',
      updated_at: '2024-05-13T13:11:10.355413+01:00',
      publish: false,
      rejected: false,
      request_for_publish: true,
      publish_to_store: true,
      rejection_reason: null,
      photo_urls: ['https://d1tfxqgzlmg1r3.cloudfront.net/FWRYvLGkwg.jpeg'],
      open_to_subscription: false,
      star_rating: 0,
      fraction_is_available: false,
      open_house_date: null,
      is_private: false,
      project_archived: false,
      total_archive: null,
      internal_commission_rate: '2.00',
      external_commission_rate: '3.00',
      current_fraction_price: '0.00',
      business: 213,
      reels: [],
    },
    allocation: null,
    co_owners: [],
    fractional_equity_value: null,
    amount_of_fractions: null,
    fractions_amount_paid: null,
    owner: {
      customer_info: null,
      id: 1258,
      bvn: null,
      agent_id: null,
      username: null,
      approved_at: null,
      date_of_birth: '2006-04-07',
      first_name: 'Joseph',
      last_name: 'Oladokun',
      middle_name: 'Abidemi',
      user_status: 'Active',
      phone: '+23408132470992',
      is_mfa: false,
      avatar: 'https://matador-bucket.s3.amazonaws.com/media/4bd539d8-0b5.png',
      monthly_income: null,
      email: 'mistyladee00@gmail.com',
      address: null,
      gender: 'Male',
      occupation: null,
      marital_status: null,
      company_name: null,
      yearly_income: null,
      highest_education: null,
      employment_status: null,
      sign_up_time: '2024-04-02T15:15:49.231657+01:00',
      company_address: null,
    },
    payment_status: 'defaulting',
    can_allocate: false,
    extra_coownership_data: null,
    equity_fees: [],
    customer: {
      id: 886,
      avatar: 'https://matador-bucket.s3.amazonaws.com/media/customer_avatar/8b89848f-72d.png',
      active: false,
      customer_ref: null,
      blacklisted: false,
      refunded_balance: '0.00',
      utility_bill: 'https://matador-bucket.s3.amazonaws.com/media/Raw%20content',
      utility_bill_updated_at: null,
      is_tier3: false,
      gender: 'Male',
      referred_at: '2024-06-22T16:27:29.744309+01:00',
      created_at: '2024-06-22T16:27:29.744330+01:00',
      password:
        'pbkdf2_sha256$260000$CSoU8F98YdMjdqqB1uHK1z$HxaBe9hxxHYhvRA1lgITcqQAFlDDI0XJlHE0CE+4aM4=',
      highest_education: null,
      address: null,
      employment_status: null,
      monthly_income: null,
      yearly_income: null,
      occupation: null,
      marital_status: null,
      company_name: null,
      company_address: null,
      email: 'mistyladee00@gmail.com',
      first_name: 'Joseph ',
      last_name: 'Oladokun ',
      middle_name: 'Abidemi ',
      phone: '8132470992',
      year_of_birth: null,
      bvn: null,
      email_verified: false,
      date_of_birth: null,
      outreach: null,
      username: null,
      extended_user: true,
      biometric_authentication: false,
      is_blocked: false,
      status: false,
      push_notification_allowed: false,
      user: 1258,
      developer: 1330,
      business: 213,
      referred_by: null,
      country: 1,
      created_by: null,
    },
    customer_co_owners: [],
    validation_requests: [],
    approved_agent: null,
    purchase_date: null,
    offer_by: null,
    total_due_balance: 100,
    offer_price: 700,
    transaction_fee: '0.00',
    is_disputed: false,
    fractions_distributed: 0,
    fractions_left: 0,
    total_unit_price: '700.00',
    auto_debit: false,
    auto_pay: false,
    next_due_balance: '100.00',
    next_due_date: '2024-07-22T22:28:38.543557+01:00',
    payment_complete: false,
    amount_paid: '100.00',
    created_at: '2024-06-23T22:21:11.080052+01:00',
    current_outstanding_balance: '600.00',
    status: 'PAID',
    type: 'WHOLE',
    auto_debit_frequency: 'DAILY',
    auto_debit_source: 'card',
    deed_requested: false,
    deed_title: null,
    deed_file: null,
    auto_debit_amount: '0.00',
    deed_granted: false,
    start_date: null,
    final_due_date: '2024-12-20T22:21:11.077533+01:00',
    purchased_from_matador: false,
    equity_value: 100,
    equity_value_invitable: 100,
    requested_at: null,
    uploaded_at: null,
    offer_expires: '2024-06-24T22:21:11.079441+01:00',
    offer_started: true,
    all_invitees_accepted: false,
    matador_junior: false,
    has_generated_upcoming: true,
    is_offer: false,
    deduct_from: 'available',
    card: null,
    uploaded_by: null,
    initiator: null,
    co_parent: [],
    account_numbers: [],
  },
];

export const default_user = {
  id: 886,
  user: {
    id: 1258,
    avatar: 'https://matador-bucket.s3.amazonaws.com/media/4bd539d8-0b5.png',
    id_document: null,
    proof_of_address: null,
    next_of_kin: null,
    bank_accounts: [],
    role: null,
    team_status: null,
    team_company_name: null,
    in_review: false,
    expected_activities: false,
    trial_days: 0,
    trial_display: false,
    is_owner: false,
    developer_link: null,
    last_login: '2024-10-10T14:18:57.915698+01:00',
    username: null,
    bvn: null,
    year_of_birth: null,
    parents_ids: null,
    date_of_birth: '2006-04-07',
    email: 'mistyladee00@gmail.com',
    first_name: 'Joseph',
    lang: null,
    last_name: 'Oladokun',
    middle_name: 'Abidemi',
    phone: '08132470992',
    status: true,
    is_blocked: false,
    gender: 'Male',
    address: null,
    yearly_income: null,
    employment_status: null,
    monthly_income: null,
    occupation: null,
    marital_status: null,
    company_name: null,
    company_address: null,
    cac_number: null,
    highest_education: null,
    referral_code: 'Nt7RdY',
    push_notification_id: null,
    enable_2fa: false,
    recovery_code: null,
    is_qualified_for_line_of_credit: false,
    is_qualified_for_mortgage: false,
    last_contact_update: null,
    push_notification_allowed: false,
    biometric_authentication: false,
    is_private: false,
    about_dev: null,
    initial_status: 'Pending',
    passward_change_time: null,
    referred_by: null,
    sign_up_time: '2024-04-02T15:15:49.231657+01:00',
    dynamic_referral: 'https://refer.matadortrust.com/fDprvvAcyiHFxkbj6',
    is_tier3: false,
    use_security_question: false,
    security_question: null,
    security_answer: null,
    developer_feedback: null,
    referral_status: 'Pending',
    outreach: null,
    agent_id: null,
    invite_code: 'I3Cm0MKzXm',
    co_parent_invite: 'https://refer.matadortrust.com/v23RiMLm15YigecQ8',
    mfa_secret: '{"message":"This endpoint is disabled for your subscription"}',
    is_mfa: false,
    last_activity: null,
    approved_at: null,
    country: 1,
    annual_income: null,
    channel: null,
    groups: [2],
  },
  developer: {
    id: 1330,
    avatar: 'https://matador-bucket.s3.amazonaws.com/media/eb3575de-82e.jpeg',
    id_document: null,
    proof_of_address: null,
    next_of_kin: null,
    bank_accounts: [],
    role: 'Admin',
    team_status: 'accepted',
    team_company_name: 'Landwey',
    in_review: false,
    expected_activities: true,
    trial_days: 0,
    trial_display: true,
    is_owner: true,
    developer_link: null,
    last_login: '2024-10-01T23:14:09.043091+01:00',
    username: null,
    bvn: '22461761443',
    year_of_birth: null,
    parents_ids: null,
    date_of_birth: null,
    email: 'johemas161@deligy.com',
    first_name: 'Joseph',
    lang: null,
    last_name: 'Oladokun',
    middle_name: null,
    phone: '+2348132470992',
    status: true,
    is_blocked: false,
    gender: null,
    address: null,
    yearly_income: null,
    employment_status: null,
    monthly_income: null,
    occupation: null,
    marital_status: null,
    company_name: 'Landwey',
    company_address: 'Km 42, Lekki-Epe Express Way, Oko-Ado, Sangotedo, Ajah, Lagos',
    cac_number: '',
    highest_education: null,
    referral_code: 'i81JwJ',
    push_notification_id: null,
    enable_2fa: false,
    recovery_code: 'q1Q2g4',
    is_qualified_for_line_of_credit: false,
    is_qualified_for_mortgage: false,
    last_contact_update: null,
    push_notification_allowed: false,
    biometric_authentication: false,
    is_private: false,
    about_dev: null,
    initial_status: 'Accepted',
    passward_change_time: null,
    referred_by: null,
    sign_up_time: '2024-05-02T18:13:49.199154+01:00',
    dynamic_referral: null,
    is_tier3: false,
    use_security_question: false,
    security_question: null,
    security_answer: null,
    developer_feedback: null,
    referral_status: 'Pending',
    outreach: null,
    agent_id: null,
    invite_code: null,
    co_parent_invite: null,
    mfa_secret: '{"message":"This endpoint is disabled for your subscription"}',
    is_mfa: false,
    last_activity: '2024-10-01T23:14:09.048402+01:00',
    approved_at: '2024-05-02T18:18:14.859756+01:00',
    country: 1,
    annual_income: null,
    channel: null,
    groups: [37],
  },
  phone: '+2348132470992',
  sign_up_time: '2024-06-22T15:27:29.744330Z',
  avatar: 'https://matador-bucket.s3.amazonaws.com/media/customer_avatar/8b89848f-72d.png',
  first_name: 'Joseph ',
  last_name: 'Oladokun ',
  documents: [
    {
      id: 196,
      document: 'https://matador-bucket.s3.amazonaws.com/media/extended_document/af216e8d-f39.pdf',
      store: 'landwey',
      created_at: '2024-08-19T12:49:30.633401+01:00',
      extended_user: 886,
    },
  ],
  active: false,
  customer_ref: null,
  blacklisted: false,
  refunded_balance: '0.00',
  utility_bill: 'https://matador-bucket.s3.amazonaws.com/media/Raw%20content',
  utility_bill_updated_at: null,
  is_tier3: false,
  gender: 'Male',
  referred_at: '2024-06-22T16:27:29.744309+01:00',
  created_at: '2024-06-22T16:27:29.744330+01:00',
  password:
    'pbkdf2_sha256$260000$CSoU8F98YdMjdqqB1uHK1z$HxaBe9hxxHYhvRA1lgITcqQAFlDDI0XJlHE0CE+4aM4=',
  highest_education: null,
  address: null,
  employment_status: null,
  monthly_income: null,
  yearly_income: null,
  occupation: null,
  marital_status: null,
  company_name: null,
  company_address: null,
  email: 'mistyladee00@gmail.com',
  middle_name: 'Abidemi ',
  year_of_birth: null,
  bvn: null,
  email_verified: false,
  date_of_birth: null,
  outreach: null,
  username: null,
  extended_user: true,
  biometric_authentication: false,
  is_blocked: false,
  status: false,
  push_notification_allowed: false,
  business: 213,
  referred_by: null,
  country: 1,
  created_by: null,
};
