export const settings_input_field_style = {
  borderRadius: `8px`,
  height: `53px`,
  bg: `matador_background.100`,
  border: `1px solid`,
  borderColor: `matador_border_color.100`,
  boxShadow: `0px 1px 2px 0px rgba(16, 24, 40, 0.05)`,
  padding: `13px 14px`,
  color: `matador_form.label`,
  fontSize: `14px`,
  fontWeight: `400`,
  lineHeight: `150%`,
  letterSpacing: `0.28px`,
  _placeholder: {
    color: `matador_form.label`,
    fontSize: `14px`,
    fontWeight: `400`,
    lineHeight: `150%`,
    letterSpacing: `0.28px`,
  },
  labelStyles: {
    fontSize: `16px`,
    color: `matador_form.label`,
    fontWeight: `400`,
    lineHeight: `140%`,
  },
};
export const settings_select_field_style = {
  borderRadius: `8px`,
  h: `53px`,
  bg: `matador_background.100`,
  border: `1px solid`,
  borderColor: `matador_border_color.100 !important`,
  boxShadow: `0px 1px 2px 0px rgba(16, 24, 40, 0.05)`,
  color: `matador_form.label`,
  fontSize: `14px`,
  fontWeight: `400`,
  lineHeight: `150%`,
  letterSpacing: `0.28px`,
  _placeholder: {
    color: `matador_form.label`,
    fontSize: `14px`,
    fontWeight: `400`,
    lineHeight: `150%`,
    letterSpacing: `0.28px`,
  },
  labelStyles: {
    fontSize: `16px`,
    color: `matador_form.label`,
    fontWeight: `400`,
    lineHeight: `140%`,
  },
  // padding: `10px 14px`,
};
